apiVersion: kubepack.com/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: null
  name: '{{ include "vault-operator-community.fullname" . }}'
spec:
  description: Vault Operator by AppsCode - HashiCorp Vault Operator for Kubernetes
  displayName: Vault Operator Bundle
  icons:
  - src: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
    type: image/png
  links:
  - description: website
    url: https://github.com/kubevault/operator
  maintainers:
  - email: support@appscode.com
    name: appscode
  namespace: kube-system
  packages:
  - chart:
      features:
      - Vault Operator by AppsCode - HashiCorp Vault Operator for Kubernetes
      name: vault-operator
      required: true
      url: https://charts.appscode.com/stable/
      versions:
      - version: v0.4.0-beta.0
  - chart:
      features:
      - Vault Catalog by AppsCode - Catalog for Vault versions
      name: vault-catalog
      required: true
      url: https://charts.appscode.com/stable/
      versions:
      - version: v0.4.0-beta.0
  - bundle:
      name: csi-vault-community
      url: https://bundles.byte.builders/stable
      version: v2022.06.16
status: {}
