apiVersion: v2
name: csi-vault-community
description: CSI Vault Community Plan
type: application
version: v2023.9.7
appVersion: v2023.9.7
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
